### ISSUE TITLE
Scalability Y-Axis

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#11]

**Comment by herrBez** [comment]
Can we close this issue?

**Comment by gfornari** [comment]
Maybe we can add just a little paragraph under "Ethereum current state and proposals" discussing why, in our opinion, there are no proposals on this direction.

**Comment by herrBez** [comment]
Here I found a list of proposals. https://blockchainhub.net/blog/blog/scaling-ethereum-2/

**Comment by herrBez** [comment]
I totally agree

**Comment by herrBez** [comment]
Maybe we can consider truebit as a mean to scale on this axis
