### ISSUE TITLE
Separate more Kademlia description from RLPx Node Discovery description

### ISSUE THREAD

**Issue by gfornari** [herrBez/ethereum-scalability#17]
Talking about the Network Layer, we should separate more Kademlia description from RLPx Node Discovery description.

Maybe related to #16

**Comment by gfornari** [comment]
I think we should call "RLPx node discovery" instead of "Kademlia protocol" section just to put more focus on how really is Ethereum
@herrBez

**Comment by herrBez** [comment]
Ok, but 1.1.1 is a general description
