### ISSUE TITLE
Add protocols figures

### ISSUE THREAD

**Issue by gfornari** [herrBez/ethereum-scalability#18]
We could add some figures representing the protocols (or better, the interactions between them, someway), something like [this](https://fthmb.tqn.com/Rj1_beTOj53kbUVNADm5dDhSVS4=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/tcp-header-56a1adc85f9b58b7d0c1a24f.png). Useful to break the reading.

**Comment by gfornari** [comment]
Consider to redo [this](https://docs.google.com/spreadsheets/d/1aEeAzci3kcpHUyBNTU9hHFtmHH9gYxamNWh4ya9Nfqg/edit?usp=sharing) image with Google Draw

**Comment by herrBez** [comment]
If you want, you can do it. But is this really necessary? What does not convince you?

**Comment by gfornari** [comment]
Just a matter of design. Indeed we can close this :)
