### ISSUE TITLE
Add DAPP

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#21]
Add description of what is a dapp and why it is not or is decentralized in an Appendix (Because it is not part of the Ethereum Core, but includes also external services)

**Comment by herrBez** [comment]
IMHO I don't know if it is possible to add something :sweat_smile: .. we could in case transform the  subsubsection into a paragraph

**Comment by gfornari** [comment]
I think we can move it in a paragraph and close this
