### ISSUE TITLE
Decide whether to include the description of the different node types or not

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#25]
Decide whether to include the description of different node types or not.

In case we discuss the light nodes, I will suggest to add a section about the LES subprotocol.

Maybe in the Appendix we could add a little description

**Comment by herrBez** [comment]
Closing, because the pr #47  was accepted

**Comment by gfornari** [comment]
@herrBez maybe we could write how to run each node in `geth` (just the command) to give a more practical cut

**Comment by herrBez** [comment]
You are right
