### ISSUE TITLE
Test Results

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#29]
Should we also add additional information about the results? 

1. Currently, we report only the average throughput. I think that is interesting the maximal value that we can reach.

2. The average number of transaction inside a block with the different gas limits

3. The size of the state/blockchain (If I find the results, or simply the value that we can find in some sources)

**Comment by gfornari** [comment]
Yes, I think it would be good to add them and more in general expand a bit this section to give it more body

**Comment by gfornari** [comment]
Do we have other charts to add?

**Comment by gfornari** [comment]
Do we have the data to add a chart with 4 lines, one for each number of miners, with throughput on y and time on x?

**Comment by herrBez** [comment]
Throughput intended as average at time x or what? We have different runs (5 for each configuration)...
