### ISSUE TITLE
Decide the role of bold/italic/texttt text

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#34]
Decide and apply when to write a word with **bold**, *italic* or `texttt`.

Here is my proposal:

**bold**
--

I think that one could completely avoid bold font, but in our case, it should be fine (I like it), but we have to use it **only for extremely important words**

*italic*
--

When new (unconventional) words are introduced for the first time.

`code`
--

For packet-types (e.g., `Ping`, `Pong`) and program names (e.g. `geth`)?

Any comments/suggestions?

**Comment by gfornari** [comment]
Ok for me. I'd use `\emph` instead of `\textit` everywhere.

Let's do this in the last review #40

**Comment by herrBez** [comment]
Change all geth --> \texttt{geth}

**Comment by herrBez** [comment]
If you agree, we can close this issue
