### ISSUE TITLE
To scale or not to scale?

### ISSUE THREAD

**Issue by gfornari** [herrBez/ethereum-scalability#35]
Shall we change the section title?
W.r.t. the content, now we cite two references but I think we should close the section saying something like "The scalability matters"

**Comment by herrBez** [comment]
Title
---
For me it's ok, but I let you consider an alternative "The quest for scalability", although it is an implicit copy to the paper "The quest for scalability in blockchain fabric".

Content
---
1. Eventually, when you say that Ethereum can reach a throughput of 15 transactions per second we can also point to our tests that confirm this official value
2. The section is closed with this sentence 
> This shows how all the Ethereum community founders included believes that the scalability is a major concern and an actual bottleneck in the employment of the technology.

That already points out that the scalability matters. Do you have a proposal for additional/alternative sentences?

**Comment by herrBez** [comment]
Maybe we can move this section before the background. This is the Motivation for the analysis of scalability.

**Comment by herrBez** [comment]
Please consider also the title "Motivation", although I find already ok, the current title :)

**Comment by gfornari** [comment]
If we want something more classic, "Motivation" is a good alternative. Classic or atypical?

**Comment by herrBez** [comment]
Good question... Atypical?

**Comment by gfornari** [comment]
Atypical :)
