### ISSUE TITLE
Gas and payment

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#4]

**Comment by herrBez** [comment]
@gfornari take a look to what I wrote in the commit. Can we considered concluded this section or do you see something that we should add? (maybe the explanation of transactions field and/or some graphs... )?

**Comment by gfornari** [comment]
I think we have to better specify the gas role during the transaction execution, so I think it's better to move the gas discussion in Transaction execution (#5). And I agree, this is definitely the place where to put diagrams :)

**Comment by herrBez** [comment]
I added a little description of gas and payment, feel free to add more details :)

**Comment by gfornari** [comment]
Close? @herrBez
