### ISSUE TITLE
Geth redundancy

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#42]
It would be better to define one per all at the beginning of the report, that we use "go-ethereum" abbreviated as geth as a reference implementation. 

Currently, we repeat this fact a lot of time in the test and added the urls more than once.

**Comment by gfornari** [comment]
Maybe it's actually not a bad thing repeat it around the report :thinking:

**Comment by herrBez** [comment]
I would like to evaluate case by case in the review. When it sounds odd, I would change it, otherwise not

**Comment by gfornari** [comment]
Review it in the general review #40
