### ISSUE TITLE
Add in introduction a brief terminology paragraph 

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#55]
Add in the introduction a brief terminology paragraph, in which we say that for geth we intend go-ethereum implemnetation\footnote{url to go ethereum} and for hash we intend always the keccak256...

**Comment by gfornari** [comment]
For the hash, we could add a footnote at the first occurrence of it (in Kademlia protocol), like:

hash\footnote{With "hash" we always intend the Keccak-256 hash.}

**Comment by herrBez** [comment]
We can do the same for geth in my opinion, so we could also close #42

**Comment by gfornari** [comment]
Good

**Comment by herrBez** [comment]
It's already so :sunglasses:
