### ISSUE TITLE
Definition of recipe

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#56]
I don't like this definition of receipts provided in the data layer
> In [15], Vitalik Buterin 18 writes that with the receipt information, someone can answer queries like “Tell me all instances of an event of type X (e.g. a crowdfunding contract reaching its goal) emitted by this address in the past 30 days”.

#40 

Can we provide a better description?

**Comment by gfornari** [comment]
What you're quoting is not the actual definition which I think is in the previous sentence

> the receiptsRoot represents the receipts list of the transactions included in the block, which shows the effect of each transaction.

or you mean to be more formal?

**Comment by herrBez** [comment]
Yes, maybe is the fact that this description is too informal, and also that it refers to logs (which are only a part of logs).
![screenshot_20180831_125925](https://user-images.githubusercontent.com/6976484/44908933-b6f58280-ad1d-11e8-81f5-323da9642b7d.png)


But it is already ok, I cannot imagine how to improve it (without deleting it ^^).

**Comment by gfornari** [comment]
Ok, let's keep it as it is.
