### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#57]
![screenshot_20180830_222613](https://user-images.githubusercontent.com/6976484/44877266-b6200a80-aca3-11e8-9d91-f98c0317dd68.png)

My Proposal
--
There are two types of accounts:
  - **Externally Owned Account** (EOA) (referred to also simply as *accounts*)
  - **contract account** (referred to also simply as *contract*

**Comment by gfornari** [comment]
In the yellow paper Externally Owned Account never appears. I'd stick to "non-contract" (which appears)

**Comment by herrBez** [comment]
![screenshot_20180831_102717](https://user-images.githubusercontent.com/6976484/44901711-72132100-ad08-11e8-842d-36ea7bc783ba.png)

Sometimes referred to. Ok, we can say that, but I think that the main name should be externally owned account because it expresses better the fact that external entities can use them to interact with the system.

**Comment by gfornari** [comment]
I change it with

* **Externally Owned Account** (EOA) (referred to also simply as _accounts_ or _non-contract_ accounts)
* **contract account** (referred to also simply as _contract_)

ok?

**Comment by herrBez** [comment]
![image](https://user-images.githubusercontent.com/6976484/44906034-28303800-ad14-11e8-87db-fb8343a33178.png)
