### ISSUE TITLE
Caption of figure is not correct

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#58]
![screenshot_20180831_085943](https://user-images.githubusercontent.com/6976484/44897513-3b370e00-acfc-11e8-8f38-2802920b43fb.png)
A contract may call another contract through a message call. 

In addition, I am not sure if it is correct to talk about a message call when returning the result of the execution. According to the yellow paper the result is the output of a message call
![screenshot_20180831_090229](https://user-images.githubusercontent.com/6976484/44897633-9c5ee180-acfc-11e8-9325-2c87ec5ae0e0.png)

**Comment by gfornari** [comment]
For the first, yes, but it follows a code execution, then it is an execution result.
For the second, I think the focus of this diagram is the message call, if it comes contract then it is the result of some execution.

**Comment by herrBez** [comment]
Yes, but it is the answer to the call, so it is technically incorrect ( I think), to say that the contract performs a message call to return the result

**Comment by gfornari** [comment]
I think this already clarifies:

> Figure 6 shows the message call with regard to a contract account. If the destination account is a contract, the message triggers the execution of its code (Figure 6a). Instead, if the message sender is a contract, the message is the result of the code execution (Figure 6b).

**Comment by herrBez** [comment]
IMHO it could be improved. But ok, let's go on.

**Comment by gfornari** [comment]
Make a proposal so I can better understand your point
