### ISSUE TITLE
Review this list

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#59]
![screenshot_20180831_092025](https://user-images.githubusercontent.com/6976484/44898418-214afa80-acff-11e8-88e5-c66400f15390.png)

I know, that I have written this part ^^, but I think that points 2 already include points 3.
In addition the nodes should verify the whole block header and not only the nonce, e.g. they should verify that the gas limit is contained in the range
![screenshot_20180831_092547](https://user-images.githubusercontent.com/6976484/44898651-daa9d000-acff-11e8-95f9-b92f45aba3ee.png)

Moreover, we use an enumeration, but the order is surely, different. I think that my client would previously check the block header and also the nonce and only after may think to compute the transactions

**Comment by gfornari** [comment]
Let's remove 2.
In 4, let's say "checking that the block header is valid"
Change enum with itemize

**Comment by herrBez** [comment]
Rather than delete 2 I would like to merge 2 and 3. For the rest, I totally agree with u.

**Comment by herrBez** [comment]
Something like
> re-performing all transactions. This includes re-executing all EVM computations ...

**Comment by gfornari** [comment]
Good for me
