### ISSUE TITLE
JSON RPC

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#6]
Should we mentione/describe the JSON RPC?

**Comment by gfornari** [comment]
I think we should at least mention it. It's not in the Ethereum pure specification, but geth uses it.

**Comment by herrBez** [comment]
Not only geth, also parity uses it https://github.com/paritytech/jsonrpc

**Comment by herrBez** [comment]
@gfornari please take a look to what I wrote. If you agree, close the issue
