### ISSUE TITLE
ABI specification

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#60]
https://media.readthedocs.org/pdf/solidity/develop/solidity.pdf

> Although there is a common agreement on the ABI format, this abstraction is not part
of the core Ethereum protocol meaning that anyone can define and expose its own ABI,
but the caller have to comply to the format used by the callee.

I would add the reference to the solidity docs (it has a chapter about the specification)

**Comment by gfornari** [comment]
Ok, but just as an example

**Comment by herrBez** [comment]
I would simply write

> Although there is a common agreement on the ABI format~\cite{solidity}...

**Comment by gfornari** [comment]
Good
