### ISSUE TITLE
Describe block

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#7]
Descibe blocks in the architecture?

**Comment by herrBez** [comment]
IMHO we can close this issue, because this description already contained in the world state section (?)

**Comment by gfornari** [comment]
Not really. I think right now the blocks are described here and there. For example, in the _state_ section, we describe the tree hashes, while in the _Transaction Execution_ section, we mention the gas limit.

**Comment by herrBez** [comment]
Would you like to write a separate section for blocks (I would agree ^^)

**Comment by gfornari** [comment]
Let's start with the scalability first, then will see :)

**Comment by herrBez** [comment]
I think that we could simply add a reference to the yellow paper and refer to section "Test" in which we describe only the interesting ones for scalability

**Comment by gfornari** [comment]
Have we already described them? :thinking:

**Comment by herrBez** [comment]
![screenshot_20180823_094158](https://user-images.githubusercontent.com/6976484/44511806-f33f3800-a6b8-11e8-8185-ae868fadb6dd.png)

I think, that by reading the report, one could get confused about why we only describe the three merkle tree field and not the other ones.

**Comment by gfornari** [comment]
I mean, have we already describe the interesting ones for the scalability in "Test"?

**Comment by herrBez** [comment]
We describe the most interesting ones (e.g. timestamp, difficulty and gas limit) inside the Test section (in the paragraph genesis file)

**Comment by gfornari** [comment]
Sorry, missed them. Nice, I agree.
