### ISSUE TITLE
Discuss this sentence

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#70]
![screenshot_20180831_180717](https://user-images.githubusercontent.com/6976484/44923502-b3c3bc00-ad48-11e8-8c12-4fb97055ea69.png)

In my opinion, it is always a drawback, because of consistency problems etc. So I would change in:
> This could seem not a drawback at first, but it becomes unmanageable if the data size increase

Or something similar

**Comment by gfornari** [comment]
I wrote it based on the Art of Scalability, but I don't find what support it anymore.
However, I think it's not a real drawback at first. I agree that would be better a stateless, but if you can't, then you have to manage to update the state accordingly, and this become a real drawback when the data size increases
