### ISSUE TITLE
Describe the Ethereum World State

### ISSUE THREAD

**Issue by herrBez** [herrBez/ethereum-scalability#8]
In my opinion, it is of fundamental importance to describe more accurately the World State and its component. This makes it clear that this system is very difficult to scale and prone to centralization because the world state is a big piece of data.

**Comment by herrBez** [comment]
In my opinion this image is very clear and we could use it in the report:
https://i.stack.imgur.com/QpcFh.png

**Comment by gfornari** [comment]
I agree about deeply describe the World State. I think we can use that image after reading https://blog.ethereum.org/2015/06/26/state-tree-pruning/. Maybe we ca simplify a bit the diagram (e.g. removing the specification of what "Uncles Hash" is).

**Comment by herrBez** [comment]
IMHO, we can consider close this issue?
